/********************************************************************
* rootcint/rootdictInfoClasses.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootcint/rootdictInfoClasses.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootdictInfoClasses();
extern void G__cpp_setup_inheritancerootdictInfoClasses();
extern void G__cpp_setup_typetablerootdictInfoClasses();
extern void G__cpp_setup_memvarrootdictInfoClasses();
extern void G__cpp_setup_globalrootdictInfoClasses();
extern void G__cpp_setup_memfuncrootdictInfoClasses();
extern void G__cpp_setup_funcrootdictInfoClasses();
extern void G__set_cpp_environmentrootdictInfoClasses();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/SKsumClass.h"
#include "include/SKbeamClass.h"
#include "include/bsdclass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootdictInfoClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootdictInfoClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictInfoClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootdictInfoClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rootdictInfoClassesLN_TTree;
extern G__linked_taginfo G__rootdictInfoClassesLN_TBranch;
extern G__linked_taginfo G__rootdictInfoClassesLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__rootdictInfoClassesLN_SKsumClass;
extern G__linked_taginfo G__rootdictInfoClassesLN_SKbeamClass;
extern G__linked_taginfo G__rootdictInfoClassesLN_bsdclass;

/* STUB derived class for protected member access */
