//
// File generated by rootcint at Thu Jul 11 21:27:01 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME rootcintdIrootdictInfoClasses
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "rootdictInfoClasses.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void SKsumClass_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void SKsumClass_Dictionary();
   static void *new_SKsumClass(void *p = 0);
   static void *newArray_SKsumClass(Long_t size, void *p);
   static void delete_SKsumClass(void *p);
   static void deleteArray_SKsumClass(void *p);
   static void destruct_SKsumClass(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SKsumClass*)
   {
      ::SKsumClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::SKsumClass),0);
      static ::ROOT::TGenericClassInfo 
         instance("SKsumClass", "./include/SKsumClass.h", 15,
                  typeid(::SKsumClass), DefineBehavior(ptr, ptr),
                  0, &SKsumClass_Dictionary, isa_proxy, 0,
                  sizeof(::SKsumClass) );
      instance.SetNew(&new_SKsumClass);
      instance.SetNewArray(&newArray_SKsumClass);
      instance.SetDelete(&delete_SKsumClass);
      instance.SetDeleteArray(&deleteArray_SKsumClass);
      instance.SetDestructor(&destruct_SKsumClass);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SKsumClass*)
   {
      return GenerateInitInstanceLocal((::SKsumClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SKsumClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void SKsumClass_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::SKsumClass*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void SKbeamClass_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void SKbeamClass_Dictionary();
   static void *new_SKbeamClass(void *p = 0);
   static void *newArray_SKbeamClass(Long_t size, void *p);
   static void delete_SKbeamClass(void *p);
   static void deleteArray_SKbeamClass(void *p);
   static void destruct_SKbeamClass(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SKbeamClass*)
   {
      ::SKbeamClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::SKbeamClass),0);
      static ::ROOT::TGenericClassInfo 
         instance("SKbeamClass", "./include/SKbeamClass.h", 15,
                  typeid(::SKbeamClass), DefineBehavior(ptr, ptr),
                  0, &SKbeamClass_Dictionary, isa_proxy, 0,
                  sizeof(::SKbeamClass) );
      instance.SetNew(&new_SKbeamClass);
      instance.SetNewArray(&newArray_SKbeamClass);
      instance.SetDelete(&delete_SKbeamClass);
      instance.SetDeleteArray(&deleteArray_SKbeamClass);
      instance.SetDestructor(&destruct_SKbeamClass);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SKbeamClass*)
   {
      return GenerateInitInstanceLocal((::SKbeamClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SKbeamClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void SKbeamClass_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::SKbeamClass*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void bsdclass_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void bsdclass_Dictionary();
   static void *new_bsdclass(void *p = 0);
   static void *newArray_bsdclass(Long_t size, void *p);
   static void delete_bsdclass(void *p);
   static void deleteArray_bsdclass(void *p);
   static void destruct_bsdclass(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::bsdclass*)
   {
      ::bsdclass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::bsdclass),0);
      static ::ROOT::TGenericClassInfo 
         instance("bsdclass", "./include/bsdclass.h", 14,
                  typeid(::bsdclass), DefineBehavior(ptr, ptr),
                  0, &bsdclass_Dictionary, isa_proxy, 0,
                  sizeof(::bsdclass) );
      instance.SetNew(&new_bsdclass);
      instance.SetNewArray(&newArray_bsdclass);
      instance.SetDelete(&delete_bsdclass);
      instance.SetDeleteArray(&deleteArray_bsdclass);
      instance.SetDestructor(&destruct_bsdclass);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::bsdclass*)
   {
      return GenerateInitInstanceLocal((::bsdclass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::bsdclass*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void bsdclass_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::bsdclass*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_SKsumClass(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SKsumClass : new ::SKsumClass;
   }
   static void *newArray_SKsumClass(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SKsumClass[nElements] : new ::SKsumClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_SKsumClass(void *p) {
      delete ((::SKsumClass*)p);
   }
   static void deleteArray_SKsumClass(void *p) {
      delete [] ((::SKsumClass*)p);
   }
   static void destruct_SKsumClass(void *p) {
      typedef ::SKsumClass current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::SKsumClass

namespace ROOT {
   // Wrappers around operator new
   static void *new_SKbeamClass(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SKbeamClass : new ::SKbeamClass;
   }
   static void *newArray_SKbeamClass(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SKbeamClass[nElements] : new ::SKbeamClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_SKbeamClass(void *p) {
      delete ((::SKbeamClass*)p);
   }
   static void deleteArray_SKbeamClass(void *p) {
      delete [] ((::SKbeamClass*)p);
   }
   static void destruct_SKbeamClass(void *p) {
      typedef ::SKbeamClass current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::SKbeamClass

namespace ROOT {
   // Wrappers around operator new
   static void *new_bsdclass(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::bsdclass : new ::bsdclass;
   }
   static void *newArray_bsdclass(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::bsdclass[nElements] : new ::bsdclass[nElements];
   }
   // Wrapper around operator delete
   static void delete_bsdclass(void *p) {
      delete ((::bsdclass*)p);
   }
   static void deleteArray_bsdclass(void *p) {
      delete [] ((::bsdclass*)p);
   }
   static void destruct_bsdclass(void *p) {
      typedef ::bsdclass current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::bsdclass

/********************************************************
* rootcint/rootdictInfoClasses.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablerootdictInfoClasses();

extern "C" void G__set_cpp_environmentrootdictInfoClasses() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("include/SKsumClass.h");
  G__add_compiledheader("include/SKbeamClass.h");
  G__add_compiledheader("include/bsdclass.h");
  G__cpp_reset_tagtablerootdictInfoClasses();
}
#include <new>
extern "C" int G__cpp_dllrevrootdictInfoClasses() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SKsumClass */
static int G__rootdictInfoClasses_522_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SKsumClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SKsumClass((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) SKsumClass((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SKsumClass[n];
       } else {
         p = new((void*) gvp) SKsumClass[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SKsumClass;
       } else {
         p = new((void*) gvp) SKsumClass;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKsumClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_522_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((SKsumClass*) G__getstructoffset())->Cut((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_522_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((SKsumClass*) G__getstructoffset())->GetEntry((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_522_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((SKsumClass*) G__getstructoffset())->LoadTree((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_522_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SKsumClass*) G__getstructoffset())->Init((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_522_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SKsumClass*) G__getstructoffset())->Loop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_522_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SKsumClass*) G__getstructoffset())->Notify());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_522_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((SKsumClass*) G__getstructoffset())->Show((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((SKsumClass*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__rootdictInfoClasses_522_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SKsumClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SKsumClass(*(SKsumClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKsumClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SKsumClass G__TSKsumClass;
static int G__rootdictInfoClasses_522_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SKsumClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SKsumClass*) (soff+(sizeof(SKsumClass)*i)))->~G__TSKsumClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SKsumClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SKsumClass*) (soff))->~G__TSKsumClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__rootdictInfoClasses_522_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SKsumClass* dest = (SKsumClass*) G__getstructoffset();
   *dest = *(SKsumClass*) libp->para[0].ref;
   const SKsumClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* SKbeamClass */
static int G__rootdictInfoClasses_523_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SKbeamClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SKbeamClass((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) SKbeamClass((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SKbeamClass[n];
       } else {
         p = new((void*) gvp) SKbeamClass[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SKbeamClass;
       } else {
         p = new((void*) gvp) SKbeamClass;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKbeamClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_523_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((SKbeamClass*) G__getstructoffset())->Cut((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_523_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((SKbeamClass*) G__getstructoffset())->GetEntry((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_523_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((SKbeamClass*) G__getstructoffset())->LoadTree((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_523_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SKbeamClass*) G__getstructoffset())->Init((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_523_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SKbeamClass*) G__getstructoffset())->Loop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_523_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SKbeamClass*) G__getstructoffset())->Notify());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_523_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((SKbeamClass*) G__getstructoffset())->Show((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((SKbeamClass*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__rootdictInfoClasses_523_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SKbeamClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SKbeamClass(*(SKbeamClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKbeamClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SKbeamClass G__TSKbeamClass;
static int G__rootdictInfoClasses_523_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SKbeamClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SKbeamClass*) (soff+(sizeof(SKbeamClass)*i)))->~G__TSKbeamClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SKbeamClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SKbeamClass*) (soff))->~G__TSKbeamClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__rootdictInfoClasses_523_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SKbeamClass* dest = (SKbeamClass*) G__getstructoffset();
   *dest = *(SKbeamClass*) libp->para[0].ref;
   const SKbeamClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* bsdclass */
static int G__rootdictInfoClasses_524_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   bsdclass* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new bsdclass((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) bsdclass((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new bsdclass[n];
       } else {
         p = new((void*) gvp) bsdclass[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new bsdclass;
       } else {
         p = new((void*) gvp) bsdclass;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictInfoClassesLN_bsdclass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_524_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((bsdclass*) G__getstructoffset())->Cut((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_524_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((bsdclass*) G__getstructoffset())->GetEntry((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_524_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((bsdclass*) G__getstructoffset())->LoadTree((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_524_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((bsdclass*) G__getstructoffset())->Init((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_524_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((bsdclass*) G__getstructoffset())->Loop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_524_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((bsdclass*) G__getstructoffset())->Notify());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdictInfoClasses_524_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((bsdclass*) G__getstructoffset())->Show((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((bsdclass*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__rootdictInfoClasses_524_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   bsdclass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new bsdclass(*(bsdclass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictInfoClassesLN_bsdclass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef bsdclass G__Tbsdclass;
static int G__rootdictInfoClasses_524_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (bsdclass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((bsdclass*) (soff+(sizeof(bsdclass)*i)))->~G__Tbsdclass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (bsdclass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((bsdclass*) (soff))->~G__Tbsdclass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__rootdictInfoClasses_524_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   bsdclass* dest = (bsdclass*) G__getstructoffset();
   *dest = *(bsdclass*) libp->para[0].ref;
   const bsdclass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SKsumClass */

/* SKbeamClass */

/* bsdclass */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrootdictInfoClasses {
 public:
  G__Sizep2memfuncrootdictInfoClasses(): p(&G__Sizep2memfuncrootdictInfoClasses::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrootdictInfoClasses::*p)();
};

size_t G__get_sizep2memfuncrootdictInfoClasses()
{
  G__Sizep2memfuncrootdictInfoClasses a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerootdictInfoClasses() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerootdictInfoClasses() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__rootdictInfoClassesLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SKsumClass */
static void G__setup_memvarSKsumClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKsumClass));
   { SKsumClass *p; p=(SKsumClass*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->nrunsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nrunsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nsubsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nsubsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nevsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nevsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ndaysk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ndaysk[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ntimsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ntimsk[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->idtgsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"idtgsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ifevsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ifevsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nevhwsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nevhwsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->numhwsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"numhwsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ihwt0)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ihwt0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->it0sk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"it0sk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeak)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeak=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeakpre)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeakpre=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeakon)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeakon=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->swt0pre)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"swt0pre=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->swt0peak)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"swt0peak=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ihwped)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ihwped=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nqiskz)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nqiskz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nhitaz)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nhitaz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->diff_ltc1)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"diff_ltc1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->diff_ltc2)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"diff_ltc2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps1_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps1_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps1_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps1_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps2_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps2_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps2_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps2_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gpsstat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gpsstat=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_gps)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_gps=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_evstatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_evstatus=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_tq)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_tq=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_preact)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_preact=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_tdcreset)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_tdcreset=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_pedestal)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_pedestal=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nrunbm)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nrunbm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nspl)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nspl=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kltccorr)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kltccorr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps1_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps1_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps1_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps1_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps2_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps2_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps2_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps2_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgpsstat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgpsstat=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->etime)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"etime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_atmpd)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_atmpd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_t2ksk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_t2ksk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sk_quality_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"sk_quality_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_nrunsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nrunsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nsubsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nsubsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nevsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nevsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ndaysk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ndaysk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ntimsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ntimsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_idtgsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_idtgsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ifevsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ifevsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nevhwsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nevhwsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_numhwsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_numhwsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ihwt0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ihwt0=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_it0sk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_it0sk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeak)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_npeak=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeakpre)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_npeakpre=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeakon)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_npeakon=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_swt0pre)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_swt0pre=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_swt0peak)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_swt0peak=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ihwped)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ihwped=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nqiskz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nqiskz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nhitaz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nhitaz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_diff_ltc1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_diff_ltc1=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_diff_ltc2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_diff_ltc2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps1_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps1_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps1_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps1_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps2_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps2_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps2_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps2_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gpsstat)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gpsstat=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_gps)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_gps=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_evstatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_evstatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_tq)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_tq=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_preact)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_preact=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_tdcreset)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_tdcreset=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_pedestal)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_pedestal=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nrunbm)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nrunbm=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nspl)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nspl=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kltccorr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kltccorr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps1_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps1_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps1_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps1_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps2_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps2_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps2_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps2_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgpsstat)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgpsstat=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_etime)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_etime=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_atmpd)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_atmpd=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_t2ksk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_t2ksk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_sk_quality_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_sk_quality_flag=",0,"!");
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* SKbeamClass */
static void G__setup_memvarSKbeamClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKbeamClass));
   { SKbeamClass *p; p=(SKbeamClass*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->nrunsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nrunsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nsubsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nsubsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nevsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nevsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ndaysk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ndaysk[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ntimsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ntimsk[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->idtgsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"idtgsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ifevsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ifevsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nevhwsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nevhwsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->numhwsk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"numhwsk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ihwt0)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ihwt0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->it0sk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"it0sk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeak)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeak=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeakpre)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeakpre=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeakon)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeakon=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->swt0pre)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"swt0pre=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->swt0peak)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"swt0peak=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ihwped)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ihwped=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nqiskz)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nqiskz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nhitaz)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nhitaz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->diff_ltc1)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"diff_ltc1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->diff_ltc2)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"diff_ltc2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps1_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps1_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps1_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps1_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps2_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps2_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gps2_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gps2_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gpsstat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gpsstat=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_gps)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_gps=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_evstatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_evstatus=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_tq)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_tq=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_preact)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_preact=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_tdcreset)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_tdcreset=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_pedestal)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_pedestal=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nrunbm)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nrunbm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nspl)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nspl=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kltccorr)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kltccorr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps1_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps1_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps1_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps1_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps2_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps2_sec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgps2_nsec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgps2_nsec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t2kgpsstat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t2kgpsstat=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->etime)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"etime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_atmpd)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_atmpd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iflag_t2ksk)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"iflag_t2ksk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sk_quality_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"sk_quality_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nurun)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nurun=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->spillnum)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"spillnum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trg_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trg_sec[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trg_nano)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trg_nano[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trigger_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trigger_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->spill_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"spill_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->good_spill_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"good_spill_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ct_np)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ct_np[5][9]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beam_time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"beam_time[5][9]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_nrunsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nrunsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nsubsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nsubsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nevsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nevsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ndaysk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ndaysk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ntimsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ntimsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_idtgsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_idtgsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ifevsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ifevsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nevhwsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nevhwsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_numhwsk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_numhwsk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ihwt0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ihwt0=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_it0sk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_it0sk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeak)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_npeak=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeakpre)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_npeakpre=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeakon)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_npeakon=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_swt0pre)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_swt0pre=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_swt0peak)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_swt0peak=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ihwped)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ihwped=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nqiskz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nqiskz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nhitaz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nhitaz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_diff_ltc1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_diff_ltc1=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_diff_ltc2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_diff_ltc2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps1_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps1_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps1_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps1_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps2_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps2_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gps2_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gps2_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gpsstat)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gpsstat=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_gps)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_gps=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_evstatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_evstatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_tq)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_tq=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_preact)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_preact=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_tdcreset)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_tdcreset=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_pedestal)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_pedestal=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nrunbm)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nrunbm=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nspl)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nspl=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kltccorr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kltccorr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps1_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps1_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps1_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps1_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps2_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps2_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgps2_nsec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgps2_nsec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_t2kgpsstat)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_t2kgpsstat=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_etime)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_etime=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_atmpd)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_atmpd=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_iflag_t2ksk)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_iflag_t2ksk=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_sk_quality_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_sk_quality_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nurun)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nurun=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_spillnum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_spillnum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_trg_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_trg_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_trg_nano)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_trg_nano=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_trigger_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_trigger_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_spill_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_spill_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_good_spill_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_good_spill_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ct_np)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ct_np=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beam_time)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_beam_time=",0,"!");
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* bsdclass */
static void G__setup_memvarbsdclass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdictInfoClassesLN_bsdclass));
   { bsdclass *p; p=(bsdclass*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->nurun)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nurun=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->midas_event)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"midas_event=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mrrun)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mrrun=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mrshot)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mrshot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->spillnum)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"spillnum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trg_sec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trg_sec[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trg_nano)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trg_nano[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gpsstat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gpsstat[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ct_np)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ct_np[5][9]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beam_time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"beam_time[5][9]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beam_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"beam_flag[5][9]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hct)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hct[3][5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tpos)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"tpos[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tdir)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"tdir[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tsize)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"tsize[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mumon)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mumon[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->otr)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"otr[13]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->good_gps_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"good_gps_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trigger_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trigger_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->spill_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"spill_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->good_spill_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"good_spill_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_nurun)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_nurun=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_midas_event)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_midas_event=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mrrun)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_mrrun=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mrshot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_mrshot=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_spillnum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_spillnum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_trig_sec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_trig_sec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_trig_nano)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_trig_nano=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_gpsstat)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_gpsstat=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ct_np)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_ct_np=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beam_time)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_beam_time=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beam_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_beam_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_hct)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_hct=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tpos)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_tpos=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tdir)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_tdir=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tsize)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_tsize=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mumon)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_mumon=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_otr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_otr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_good_gps_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_good_gps_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_trigger_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_trigger_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_spill_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_spill_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_good_spill_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rootdictInfoClassesLN_TBranch),-1,-1,1,"b_good_spill_flag=",0,"!");
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrootdictInfoClasses() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSKsumClass(void) {
   /* SKsumClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKsumClass));
   G__memfunc_setup("SKsumClass",1001,G__rootdictInfoClasses_522_0_1, 105, G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKsumClass), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut",300,G__rootdictInfoClasses_522_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,G__rootdictInfoClasses_522_0_3, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,G__rootdictInfoClasses_522_0_4, 110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,G__rootdictInfoClasses_522_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Loop",410,G__rootdictInfoClasses_522_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,G__rootdictInfoClasses_522_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Show",417,G__rootdictInfoClasses_522_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 '-1' entry", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("SKsumClass", 1001, G__rootdictInfoClasses_522_0_9, (int) ('i'), G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKsumClass), -1, 0, 1, 1, 1, 0, "u 'SKsumClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SKsumClass", 1127, G__rootdictInfoClasses_522_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__rootdictInfoClasses_522_0_11, (int) ('u'), G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKsumClass), -1, 1, 1, 1, 1, 0, "u 'SKsumClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncSKbeamClass(void) {
   /* SKbeamClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKbeamClass));
   G__memfunc_setup("SKbeamClass",1065,G__rootdictInfoClasses_523_0_1, 105, G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKbeamClass), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut",300,G__rootdictInfoClasses_523_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,G__rootdictInfoClasses_523_0_3, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,G__rootdictInfoClasses_523_0_4, 110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,G__rootdictInfoClasses_523_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Loop",410,G__rootdictInfoClasses_523_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,G__rootdictInfoClasses_523_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Show",417,G__rootdictInfoClasses_523_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 '-1' entry", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("SKbeamClass", 1065, G__rootdictInfoClasses_523_0_9, (int) ('i'), G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKbeamClass), -1, 0, 1, 1, 1, 0, "u 'SKbeamClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SKbeamClass", 1191, G__rootdictInfoClasses_523_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__rootdictInfoClasses_523_0_11, (int) ('u'), G__get_linked_tagnum(&G__rootdictInfoClassesLN_SKbeamClass), -1, 1, 1, 1, 1, 0, "u 'SKbeamClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncbsdclass(void) {
   /* bsdclass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdictInfoClassesLN_bsdclass));
   G__memfunc_setup("bsdclass",847,G__rootdictInfoClasses_524_0_1, 105, G__get_linked_tagnum(&G__rootdictInfoClassesLN_bsdclass), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut",300,G__rootdictInfoClasses_524_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,G__rootdictInfoClasses_524_0_3, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,G__rootdictInfoClasses_524_0_4, 110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,G__rootdictInfoClasses_524_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Loop",410,G__rootdictInfoClasses_524_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,G__rootdictInfoClasses_524_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Show",417,G__rootdictInfoClasses_524_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 '-1' entry", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("bsdclass", 847, G__rootdictInfoClasses_524_0_9, (int) ('i'), G__get_linked_tagnum(&G__rootdictInfoClassesLN_bsdclass), -1, 0, 1, 1, 1, 0, "u 'bsdclass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~bsdclass", 973, G__rootdictInfoClasses_524_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__rootdictInfoClasses_524_0_11, (int) ('u'), G__get_linked_tagnum(&G__rootdictInfoClassesLN_bsdclass), -1, 1, 1, 1, 1, 0, "u 'bsdclass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrootdictInfoClasses() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrootdictInfoClasses() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrootdictInfoClasses() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rootdictInfoClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_SKsumClass = { "SKsumClass" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_SKbeamClass = { "SKbeamClass" , 99 , -1 };
G__linked_taginfo G__rootdictInfoClassesLN_bsdclass = { "bsdclass" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerootdictInfoClasses() {
  G__rootdictInfoClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rootdictInfoClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictInfoClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__rootdictInfoClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__rootdictInfoClassesLN_TTree.tagnum = -1 ;
  G__rootdictInfoClassesLN_TBranch.tagnum = -1 ;
  G__rootdictInfoClassesLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__rootdictInfoClassesLN_SKsumClass.tagnum = -1 ;
  G__rootdictInfoClassesLN_SKbeamClass.tagnum = -1 ;
  G__rootdictInfoClassesLN_bsdclass.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerootdictInfoClasses() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_TTree);
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_TBranch);
   G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_SKsumClass),sizeof(SKsumClass),-1,1280,(char*)NULL,G__setup_memvarSKsumClass,G__setup_memfuncSKsumClass);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_SKbeamClass),sizeof(SKbeamClass),-1,1280,(char*)NULL,G__setup_memvarSKbeamClass,G__setup_memfuncSKbeamClass);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdictInfoClassesLN_bsdclass),sizeof(bsdclass),-1,1280,(char*)NULL,G__setup_memvarbsdclass,G__setup_memfuncbsdclass);
}
extern "C" void G__cpp_setuprootdictInfoClasses(void) {
  G__check_setup_version(30051515,"G__cpp_setuprootdictInfoClasses()");
  G__set_cpp_environmentrootdictInfoClasses();
  G__cpp_setup_tagtablerootdictInfoClasses();

  G__cpp_setup_inheritancerootdictInfoClasses();

  G__cpp_setup_typetablerootdictInfoClasses();

  G__cpp_setup_memvarrootdictInfoClasses();

  G__cpp_setup_memfuncrootdictInfoClasses();
  G__cpp_setup_globalrootdictInfoClasses();
  G__cpp_setup_funcrootdictInfoClasses();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrootdictInfoClasses();
  return;
}
class G__cpp_setup_initrootdictInfoClasses {
  public:
    G__cpp_setup_initrootdictInfoClasses() { G__add_setup_func("rootdictInfoClasses",(G__incsetup)(&G__cpp_setuprootdictInfoClasses)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrootdictInfoClasses() { G__remove_setup_func("rootdictInfoClasses"); }
};
G__cpp_setup_initrootdictInfoClasses G__cpp_setup_initializerrootdictInfoClasses;

